package com.jobPrize.service.member.careerDescriptionContent;

import com.jobPrize.dto.member.careerDescription.CareerDescriptionContentCreateDto;
import com.jobPrize.dto.member.careerDescription.CareerDescriptionContentResponseDto;
import com.jobPrize.dto.member.careerDescription.CareerDescriptionContentUpdateDto;
import com.jobPrize.entity.member.CareerDescription;

public interface CareerDescriptionContentService {
    CareerDescriptionContentResponseDto createCareerDescriptionContent(CareerDescription careerDescription, CareerDescriptionContentCreateDto careerDescriptionContentCreateDto);
    CareerDescriptionContentResponseDto updateCareerDescriptionContent(CareerDescriptionContentUpdateDto careerDescriptionContentUpdateDto);
    void deleteCareerDescriptionContent(Long careerDescriptionContentId);
}
